ERROR: 2022-10-04 19:40:30,909: __main__ , line 25 : HTTPSConnectionPool(host='jsonplaceholder.typicode.comusers', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102a2e310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')) 
ERROR: 2022-10-04 19:40:55,941: __main__ , line 25 : HTTPSConnectionPool(host='jsonplaceholder.typicode.comusers', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103730340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')) 
